'use client'

import {Inter} from "next/font/google";
import "./globals.css";
import IsSidebarRequired from "@/components/ui/isSidebarRequired";

const inter = Inter({subsets: ["latin"]});

// export const metadata = {
//     title: "DAWG",
//     description: "Generated by create next app",
// };

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <head>
            <title>an_over_the_top_todo_list</title>
            <link rel="icon" href="favicon.ico" sizes="any"/>
        </head>
        <body className={inter.className}>
        <div className="layout">
            <IsSidebarRequired/>
            {children}
        </div>
        </body>
        </html>
    );
}