import {Inter} from "next/font/google";
import "./globals.css";
import Nav from "@/components/ui/Nav";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "DAWG",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className="dark">
        <Nav/>
        {children}
        </body>
        </html>
    );
}
